"""The orchestrator itself, up to the point where OpenFOAM would be required.

``--plan-only`` runs the real demo path - request, interpretation, scope gate,
case generation - and stops before any CFD. That makes the whole front half of
the pipeline testable without an OpenFOAM installation, including the property
that matters most: the case the DEMO generates from the natural-language
request for Case A is byte-identical to the frozen canonical reference case.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
CANONICAL = REPO_ROOT / "validation/canonical_reference"
RUNNER = REPO_ROOT / "scripts/run_nozzle_e2e.py"

OPENFOAM_INPUTS = [
    "system/blockMeshDict",
    "system/controlDict",
    "system/fvSchemes",
    "system/fvSolution",
    "constant/physicalProperties",
    "constant/momentumTransport",
    "0/p",
    "0/T",
    "0/U",
]


@pytest.fixture(scope="module")
def plan_run(tmp_path_factory):
    out = tmp_path_factory.mktemp("plan")

    env = {
        k: v
        for k, v in __import__("os").environ.items()
        if k != "GEMINI_API_KEY"
    }

    proc = subprocess.run(
        [
            sys.executable,
            str(RUNNER),
            "--case",
            "ALL",
            "--plan-only",
            "--allow-fallback",
            "--out",
            str(out),
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        env=env,
    )

    assert proc.returncode == 0, proc.stdout + proc.stderr

    return out, proc.stdout


def test_all_three_cases_plan_successfully(plan_run):
    out, _ = plan_run

    campaign = json.loads((out / "CAMPAIGN_SUMMARY.json").read_text())

    assert [c["label"] for c in campaign["cases"]] == [
        "case_A_reference",
        "case_B_geometry",
        "case_C_conditions",
    ]
    assert all(c["status"] == "PLAN_ONLY" for c in campaign["cases"])


def test_event_stream_contains_the_real_workflow_stages(plan_run):
    out, stdout = plan_run

    events = [
        json.loads(line)
        for line in (out / "case_A_reference/events.jsonl")
        .read_text()
        .strip()
        .splitlines()
    ]

    tags = [e["tag"] for e in events]

    assert tags[0] == "ORCHESTRATOR"
    assert "LLM" in tags
    assert "SCOPE GATE" in tags
    assert "CFD SETUP" in tags

    assert "[ORCHESTRATOR]" in stdout
    assert "[SCOPE GATE]" in stdout


def test_reasoning_provenance_is_recorded_and_visible(plan_run):
    out, stdout = plan_run

    calls = json.loads((out / "case_A_reference/llm_calls.json").read_text())

    assert calls, "no reasoning call was recorded"
    assert all(call["source"] == "deterministic_fallback" for call in calls)
    assert all(call["is_llm"] is False for call in calls)
    assert "<DETERMINISTIC_FALLBACK>" in stdout
    assert "<LLM:" not in stdout


def test_scope_gate_verdict_is_archived(plan_run):
    out, _ = plan_run

    for label in ("case_A_reference", "case_B_geometry", "case_C_conditions"):
        gate = json.loads((out / label / "scope_gate.json").read_text())

        assert gate["approved"] is True
        assert gate["decision"] == "IN_SCOPE"
        assert gate["authority"] == "deterministic"


def test_case_a_generated_from_the_prompt_matches_the_frozen_reference(
    plan_run, tmp_path
):
    out, _ = plan_run

    reference = tmp_path / "canonical"

    proc = subprocess.run(
        [sys.executable, "build.py", str(reference), "--scale", "1"],
        cwd=CANONICAL,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stderr

    generated = out / "case_A_reference/generated_case"

    for relative in OPENFOAM_INPUTS:
        assert (generated / relative).read_bytes() == (
            reference / relative
        ).read_bytes(), (
            f"{relative} generated by the demo path differs from the frozen "
            "canonical reference"
        )


def test_cases_b_and_c_differ_from_case_a_only_where_intended(plan_run):
    out, _ = plan_run

    def read(label, relative):
        return (
            out / label / "generated_case" / relative
        ).read_text()

    a_mesh = read("case_A_reference", "system/blockMeshDict")
    b_mesh = read("case_B_geometry", "system/blockMeshDict")
    c_mesh = read("case_C_conditions", "system/blockMeshDict")

    assert a_mesh != b_mesh, "Case B must change the geometry"
    assert a_mesh == c_mesh, "Case C must not change the geometry"

    a_p = read("case_A_reference", "0/p")
    c_p = read("case_C_conditions", "0/p")

    assert "p0 uniform 200000" in a_p
    assert "p0 uniform 220000" in c_p

    # Identical numerical recipe for all three.
    for relative in (
        "system/fvSchemes",
        "system/fvSolution",
        "constant/physicalProperties",
    ):
        assert (
            read("case_A_reference", relative)
            == read("case_B_geometry", relative)
            == read("case_C_conditions", relative)
        )


def test_the_same_pipeline_produced_all_three_cases(plan_run):
    out, _ = plan_run

    manifests = [
        json.loads(
            (out / label / "generated_case/manifest.json").read_text()
        )
        for label in (
            "case_A_reference",
            "case_B_geometry",
            "case_C_conditions",
        )
    ]

    for manifest in manifests:
        assert manifest["solver"] == "shockFluid"
        assert manifest["initialization"] == "quasi_1d_internal_only"
        assert manifest["maxCo"] == 0.4
        assert manifest["end_time"] == 0.006
        assert manifest["ambient_imposed"] is False
        assert manifest["axial_cells"] == 132
        assert manifest["radial_cells"] == 16
        assert "Parameterized derivative" in manifest["provenance"]


def test_real_llm_is_required_without_allow_fallback(tmp_path):
    env = {
        k: v
        for k, v in __import__("os").environ.items()
        if k != "GEMINI_API_KEY"
    }

    proc = subprocess.run(
        [
            sys.executable,
            str(RUNNER),
            "--case",
            "A",
            "--plan-only",
            "--out",
            str(tmp_path),
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        env=env,
    )

    assert proc.returncode != 0
    assert "GEMINI_API_KEY" in proc.stdout

    result = json.loads(
        (tmp_path / "case_A_reference/case_result.json").read_text()
    )
    assert result["status"] == "LLM_UNAVAILABLE"
